#!/bin/bash

# Check if the container is running
if ! docker ps | grep -q "interview-core-1"; then
    echo "Error: Container 'interview-core-1' is not running. Please start the containers with 'docker-compose up -d' first."
    exit 1
fi

echo -n "Generating OpenAPI schema..."
docker exec interview-core-1 bash -c python manage.py generate_swagger -o schema.json
if [ $? -eq 0 ]; then
    echo "done"
else
    echo "error:"
    echo "Failed to generate schema. Please check the container logs for more details."
    exit 1
fi

echo -n "Copying schema to frontend..."
cp ./core/schema.json ./frontend/schema.json
echo "done"

echo -n "Generating TypeScript types..."
docker exec interview-frontend-1 sh -c "npm run types"
if [ $? -eq 0 ]; then
    echo "done"
else
    echo "error:"
    echo "Failed to generate types. Please check the container logs for more details."
    exit 1
fi

echo "TypeScript types generated successfully!"