# Generated by Django 5.0.2 on 2025-05-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('state_location', models.CharField(blank=True, max_length=2, null=True)),
                ('kind', models.TextField(choices=[('other', 'Other'), ('state', 'State'), ('county', 'County'), ('city', 'City'), ('village', 'Village'), ('town', 'Town'), ('borough', 'Borough'), ('tribal_nation', 'Tribal Nation'), ('federal', 'Federal'), ('university', 'University'), ('college', 'College'), ('high_school', 'High School'), ('middle_school', 'Middle School'), ('elementary_school', 'Elementary School'), ('k12', 'K12'), ('other_school', 'Other School'), ('hospital', 'Hospital'), ('other_health', 'Other Health'), ('transit_agency', 'Transit Agency'), ('public_works', 'Public Works'), ('other_department', 'Other Department'), ('non_profit', 'Non Profit')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rfp',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='issuing_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfps.issuingorg'),
        ),
    ]
