# Generated by Django 5.0.2 on 2025-05-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfps', '0002_issuingorg_rfp_due_date_alter_rfp_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfp',
            name='updated_at',
        ),
    ]
