# Generated by Django 5.0.2 on 2025-05-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfps', '0003_remove_rfp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
